version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    restart: always