version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:5000"
    environment:
      - FLASK_APP=${FLASK_APP:-app}
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3